### ISSUE TITLE
Error in the setup.py

### ISSUE THREAD

**Issue by Cramal** [yarden-livnat/regulus#4]
Syntax error when running the setup.py at installation.

Apparently there is a  missing ')' in def get_property(prop, project):
re.search(
        r'{}\s*=\s*[\'"]([^\'"]*)[\'"]'.format(prop),
        open(os.path.join(project, "__init__.py")******)*****.read(),
    )

**Comment by yarden-livnat** [comment]
Thanks.
Code changed
